package models

import "gorm.io/gorm"

// APIKey represents an upstream provider API key
type APIKey struct {
	gorm.Model
	Name           string `gorm:"not null"`       // display name
	Key            string `gorm:"not null"`
	Provider       string `gorm:"not null"`       // openai, anthropic, gemini, custom
	BaseURL        string                         // override default base URL
	UserID         uint                           // 0 = global pool; non-zero = private pool owner
	Weight         int    `gorm:"default:1"`
	Status         string `gorm:"default:active"` // active, disabled
	AllowedModels  string `gorm:"default:*"`      // "*" or comma-separated model IDs
	RoutingEnabled bool   `gorm:"default:true"`
	RoutingRules   string `gorm:"default:\"\""`   // JSON array of enabled rule names
	// Stats
	TotalCalls     int64 `gorm:"default:0"`
	TotalTokens    int64 `gorm:"default:0"`
	LastUsed       int64 `gorm:"default:0"` // Unix timestamp
	ErrorCount     int64 `gorm:"default:0"`
}

// NexusKey is generated by users to use the proxy endpoint
type NexusKey struct {
	gorm.Model
	Key        string `gorm:"uniqueIndex;not null"`
	UserID     uint   `gorm:"not null"`
	Name       string
	Pool       string `gorm:"default:global"` // global or private
	Status     string `gorm:"default:active"` // active, disabled
	LastUsed   int64  `gorm:"default:0"`
	TotalCalls int64  `gorm:"default:0"`
}

// UsageStat records per-user per-model usage for stats
type UsageStat struct {
	gorm.Model
	UserID     uint   `gorm:"index" json:"user_id"`
	ModelName  string `gorm:"index" json:"model"`
	Provider   string `json:"provider"`
	TokensUsed int64  `json:"tokens_used"`
	CallCount  int64  `json:"call_count"`
	Date       string `gorm:"index" json:"date"`
	Hour       int    `json:"hour"`
}
